packages/superdoc/src/stores/hrbr-fields-store.js
**Please test this before merging.**
I noticed that the fields in PDF preview are not in their proper positions on the mobile, so it seems to me that the calculations are not entirely correct.
The issue can be reproduced if you open PDF preview with fields on a small screen with the zoom already changed (different from 1).
Since zoom only changes the target element (and not the page size), it seems to me that need to take the original page size and multiply it by pdf.js default scale factor (1.333), and not calculate the scale based on the current dimensions of the page element.
Before:
After:
=> fix pdf preview scale

packages/super-editor/src/extensions/field-annotation/field-annotation.js
`currentNode ` may return `null` so additional check in needed.
=> add additional checks

packages/super-editor/src/core/super-converter/v2/importer/annotationImporter.js, packages/super-editor/src/dev/components/DeveloperPlayground.vue, packages/super-editor/src/tests/export/lists/basicOrderedListExport.test.js, packages/super-editor/src/tests/export/lists/miscOrderedListExport.test.js, packages/super-editor/src/tests/import/annotationImporter.test.js
Annotations presented in the imported doc are now transformed into text nodes {{ ${displayLabel} }}
=> HAR-9081 Import existing annotations as {{ }}

packages/super-editor/src/components/toolbar/ToolbarButtonIcon.vue, packages/super-editor/src/components/toolbar/super-toolbar.js
Hi @harbournick! I did it like it's done in Word. Set default color to light grey  so when User select text and click the highlight icon it will be immediately highlighted and color picker will be offered to select a different color
=> HAR-9135 Set default color for highlight icon

packages/super-editor/src/components/SuperEditor.vue
Collaboration cursor starts to flick from time to time. 
1. Open a SuperDoc and share it with someone
2. Leave the page open for ~5 minutes.
3. Come back to the page and try to make any edits. You will see the cursor will start to flick.
The reason this happens is because we use Cloud Run for the collaboration service, and by default it times out after 5 minutes. When it times out, the connection will be lost, but our provider (hocus pocus)  will reconnect automatically.
When that happens: 
1. The `synced` event will be triggered again
2. It will call the `pollForMetaMapData` function. 
3. The `pollForMetaMapData` function will call `initEditor` again.
4. When that happens, internally we are reinitializing  `Editor.js`, and hence the error starts to happen.
Remove the listener to the …
=> HAR-8873 - fix: prevent duplicate editor initialization on collaboration sync

packages/super-editor/src/components/SuperEditor.vue
After the `synced` event is triggered, we need to ensure only the same event listener is unbind as we have other listeners for the `synced` event.
=> fix: remove only handleSynced listener after it's triggered

packages/super-editor/src/core/super-converter/SuperConverter.js, packages/super-editor/src/core/super-converter/exporter.js
-  Documents that come from google docs or have a custom.xml can fail export when we insert the superdoc ID into custom.xml. This fixes it by ensuring the schema is correct
- Fixes json to xml conversion issue for custom.xml which does not have w:t tags
=> HAR-9232 - Fix export failures from gdocs custom.xml

packages/superdoc/src/SuperDoc.vue
**Problem**: Floating comments are not correctly aligned with the selected text. There was some code in place to determine  `Math.max(96, (top - 100))`. This ensures that the floating comment won't be too close to the header, but the `-100` part was causing the misalignment. 
**Before:**
**After:**
=> HAR-9299 - Fix: improve selection bounds calculation for floating comments

packages/superdoc/src/components/CommentsLayer/FloatingComments.vue
**Problem**: When you select a floating comment it recalculates the position of them so it's aligned with the linked text. However, if you have many comments, this might cause the comment to be moved away from your current view port. 
**Solution**: We decided to stick with a quick fix and just do not recalculate the position.
=> HAR-9218 - fix: do not reposition floating comments when selected

packages/superdoc/src/components/CommentsLayer/FloatingComments.vue
**Problem**: When there are multiple comments, the selected comment might not be visible in the screen. 
**Solution**: To solve that, we are now scrolling into the element so it's on the viewport.
Note that I also changed the transition duration to `.1s` as we need to wait for the transition to complete and only then scroll to the element. Otherwise it would take `.3s` to scroll to the component.
=> HAR-9300 - fix: improve floating comments offset calculation and scrolling behavior

packages/super-editor/src/core/super-converter/SuperConverter.js
For new media we always have to create a new relationship because a new image id is generated every time.
=> HAR-9250 - fix images export

packages/super-editor/src/core/DocxZipper.js, packages/super-editor/src/core/helpers/generateDocxListAttributes.js, packages/super-editor/src/core/helpers/generateDocxRandomId.js, packages/super-editor/src/core/super-converter/v2/exporter/commentsExporter.js, packages/super-editor/src/tests/export/lists/commentExport.test.js
- Fix issue with content types becoming corrupted if any comments type is double (ie: if imported file already had it)
- Fix paraId generator to use correct 32-bit hex
=> HAR-9211 - fix content types and hex

packages/superdoc/src/core/collaboration/helpers.js
Prevent trying to connect the global superdoc ydoc connection if there is no superdocId
=> Prevent trying to connect the global superdoc ydoc connection if there is no superdocId

packages/super-editor/src/core/super-converter/v2/exporter/commentsExporter.js, packages/super-editor/src/core/super-converter/v2/importer/documentCommentsImporter.js, packages/superdoc/src/stores/comments-store.js
Import and export comments for tracked changes.
Note:
This will not work with importing suggestions from Word (there are no comments for them).
=> HAR-9383 - import and export tracked changes comments

packages/superdoc/src/components/PdfViewer/PdfViewer.vue, packages/superdoc/src/components/PdfViewer/helpers/range.js, packages/superdoc/src/core/SuperDoc.js
- PDF text layer is optional and can be enabled/disabled via config.
- Call necessary destroy methods.
- Call `URL.revokeObjectURL` on the worker otherwise a new worker is created each time (and the old one is not destroyed).
- Fix SD destroy method to unmount the app.
- Other minor improvements.
=> HAR-9411 - optimize pdf viewer

packages/super-editor/src/core/super-converter/exporter.js, packages/super-editor/src/core/super-converter/v2/importer/markImporter.js, packages/super-editor/src/core/super-converter/v2/importer/paragraphNodeImporter.js, packages/super-editor/src/extensions/text-indent/text-indent.js, packages/super-editor/src/tests/import/listImporter.test.js
The first line indent should not be mixed and used for the overall indentation of the entire paragraph.
=> HAR-9430 - fix paragraph text indentation

packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js, packages/super-editor/src/extensions/pagination/pagination.js
Refactor header/footer import logic to account for documents that have multiple <w:sectPr> tags across document.xml
=> Refactor header/footer import logic

packages/super-editor/src/core/super-converter/SuperConverter.js
@harbournick This document from Ideals has font inconsistencies but document itself has no font definitions. SD renders Arial but Word has Times new roman. As far as I understood it uses 'Normal' styles for paragraphs and 'Heading 1'. Probably this document was created in older version of Word which had Times new roman as default font but I didn't find any signs of it in xml
=> Fix parsing error in Ideals doc

CONTRIBUTING.md
This PR corrects a mistake in the `CONTRIBUTING.md` guide. 
The git clone URL previously used a placeholder (`your-username`) instead of the official repository link. It has been updated to:
` git clone https://github.com/Harbour-Enterprises/SuperDoc.git`
This helps contributors clone the repository without confusion.
=> Fix incorrect Git clone URL in CONTRIBUTING.md

packages/super-editor/src/extensions/pagination/pagination.js
Show default header/footer for the first page.
Previous changes probably addressed some specific document issue, related to compatibility for example. But these changes raise header/footer issue for many other docs.
For reference.
https://github.com/Harbour-Enterprises/SuperDoc/pull/492/files.
=> HAR-9669 - fix header and footer for first page

packages/super-editor/src/extensions/table/table.js
Add zero width text to empty cell when create a table in order to apply marks to the text.
Note: please check my comment in the ticket before merging.
=> HAR-9663 - add zero width text when create a table

examples/vue-fields-example/src/App.vue, packages/superdoc/src/core/SuperDoc.js
- Adds isFinalDoc to superdoc's export() and passes it down to the existing editor.exportDocx()
- updates example
=> Add isFinalDoc flag in SuperDoc export

examples/typescript-example/src/components/DocumentEditor.tsx, packages/super-editor/package.json, packages/super-editor/src/core/Editor.js, packages/superdoc/package.json
- Fixes types export in super-editor package
- Adds initial types for new annotate() function in super-editor
- Fixes super-editor type defs roll up in SuperDoc
=> Fix editor type exports when rolling into SuperDoc, add annotate() types

packages/super-editor/src/core/super-converter/v2/importer/paragraphNodeImporter.js, packages/super-editor/src/extensions/paragraph/helpers/getDefaultSpacing.js, packages/super-editor/src/extensions/paragraph/paragraph.js
Paragraphs must have default spacing with zero margin, otherwise there may be spacing issues on the next import.
Here are some cases where this can happen:
1. We import a docx file that has a default margin for paragraphs (in default styles). When creating a table, paragraphs inside have no margins. During the next import, we go through the style chain - inline attributes (margin not found), but it is found in default styles and will be applied to the paragraph.
2. We import a docx file in which formatting styles are defined by id (heading1, heading2, etc). Next, we create new paragraphs (they don’t have margins) and apply formatting styles to them, for example Heading 2. On the next import we go through the style chain - inline margins are not found, but they are found by the formatting …
=> HAR-9516, HAR-9571 - add default spacing to paragraph

packages/super-editor/src/core/InputRule.js, packages/super-editor/src/extensions/line-break/line-break.js
- Remove unnecessary / forbidden tags when pasting HTML into the editor
- remove tags with linebreaktype in HTML as they are not used here and cause issues
- Make DOM parsing definition for hard break more strict
=> HAR-9905 - Fix html paste turning empty spans into page breaks

packages/super-editor/src/core/helpers/annotator.js, packages/super-editor/src/extensions/field-annotation/field-annotation.js
Extended schema, added `defaultDisplayLabel` attribute, which will be filled with `displayLabel` attr value when the annotation is added.
Commands added:
- `replaceFieldAnnotationsWithLabel` - Convert annotations back to text node.
- `replaceFieldAnnotationsWithLabelInSelection` - Convert annotations back to text node (In selection).
- `resetFieldAnnotations` - Reset all annotations to default value.
Helpers added:
- `resetHeaderFooterFieldAnnotations` - Reset all annotations to default value (in header/footer).
=> HAR-9857, HAR-9832 - field annotation commands

packages/super-editor/src/components/slash-menu/SlashMenu.vue
- prevents our custom menu from opening on right click if control key is also held
=> feat: prevent custom menu from opening when user holds control

packages/super-editor/src/components/toolbar/super-toolbar.js, packages/super-editor/src/tests/toolbar/updateToolbarState.test.js
- Ensure linked styles doesn't override the active mark
- Add initial tests for the toolbar
=> HAR-9854 - fix: text mark font family precedes linked style

packages/super-editor/src/components/SuperEditor.vue, packages/super-editor/src/extensions/slash-menu/slash-menu.js, packages/superdoc/src/SuperDoc.vue, packages/superdoc/src/core/SuperDoc.js, packages/superdoc/src/dev/components/SuperdocDev.vue
- Do not install plugin if headless or disabled
- Do not render slash menu if disable flag exists in SuperDoc config
=> feat: add disableContextMenu option to SuperDoc

packages/super-editor/src/extensions/collaboration/collaboration.js
Problem: Editor becomes uneditable every time a couple seconds after you make a change. This is happening because we're locking it, even though we shouldn't.
Fix: Since this is happening with customers at the moment, we need some more time to investigate and do a proper fix. I'm proposing we release a new version at least so we can unblock our customers and have some more time to investigate how to put back the locking mechanism.
=> HAR-9972 - SuperDoc freezing after edit

packages/super-editor/src/extensions/table/table.js
I noticed that some tables may have smaller cell widths than specified in the options.
=> update table cellMinWidth

packages/super-editor/src/core/super-converter/exporter.js, packages/super-editor/src/core/super-converter/v2/importer/listImporter.js, packages/super-editor/src/core/super-converter/v2/importer/markImporter.js, packages/super-editor/src/core/super-converter/v2/importer/paragraphNodeImporter.js, packages/super-editor/src/extensions/list-item/ListItemNodeView.js, packages/super-editor/src/extensions/table/table.js, packages/super-editor/src/extensions/text-transform/text-transform.js
Null handling issue in list translation logic causing annotation failures.
Added null safety checks in translateList function in exporter.js:
- Early null check with fallback paragraph structure
- Optional chaining for all property access
- Default values to prevent undefined errors
=> fix: improve null handling and clean up code in translateList

packages/super-editor/src/core/super-converter/exporter.js
Fixed annotations export in list items.
Notes:
- In the test document I found such elements that are processed as `structuredContent` node (with empty annotation attributes in `w:tag`) during import/export. I have no idea how these elements ended up there, and I have not been able to reproduce anything like this.
```xml
<w:sdt>
<w:sdtPr>
<w:alias w:val="undefined" />
<w:tag w:val="{&quot;displayLabel&quot;:&quot;&quot;,&quot;defaultDisplayLabel&quot;:&quot;&quot;,&quot;fieldId&quot;:&quot;agreementinput-1721689698154-41701942325&quot;,&quot;fieldType&quot;:&quot;TEXTINPUT&quot;,&quot;fieldTypeShort&quot;:&quot;text&quot;,&quot;fieldColor&quot;:&quot;#00000000&quot;,&quot;fieldMultipleImage&quot;:&quot;false&quot;,&quot;fieldFontFamily&quot;:&quot;Arial&quot;,&quot;fieldFontSize&quot;:&quot …
```
=> HAR-10236 - fix annotations export in list

packages/super-editor/src/core/Editor.js, packages/super-editor/src/core/ExtensionService.js
- Extends the extensions service and editor to allow addHelpers in extensions
- adds editor.helpers with extension namespace
=> feat: extend editor to allow addHelpers in extensions

.github/workflows/pull-request.yml
We currently have the unit tests being executed by another workflow. See [.github/workflows/ci.yml](https://github.com/Harbour-Enterprises/SuperDoc/blob/develop/.github/workflows/ci.yml#L42).
This removes this duplication.
=> fix: removed duplicate unit tests on CI/CD

packages/super-editor/src/core/Editor.js, packages/super-editor/src/core/super-converter/SuperConverter.js, packages/super-editor/src/core/super-converter/exporter.js, packages/super-editor/src/core/super-converter/getFieldHighlightJson.test.js, packages/superdoc/src/core/SuperDoc.js
- Revert exported fields to have transparent background by default
- Adds _fieldsHighlightColor_ config at export time (expects hex)
- Adds unit tests for field color generation
=> feat: default field export background transparent, allow config on export

packages/super-editor/src/extensions/block-node/block-node.js, packages/super-editor/src/extensions/block-node/block-node.test.js, packages/super-editor/src/extensions/content-block/content-block.js
- add hasInitialized check to run plugin on first render
- adds utilities to better determine which nodes to process
- adds checkForNewBlockNodesInTrs to only run the full-document parsing logic if the transaction has created a new node of interest
=> Feature: Block node IDs utilities, add hasInitialized to run plugin when first loaded

packages/super-editor/src/components/SuperEditor.vue, packages/super-editor/src/dev/components/BasicUpload.vue, packages/super-editor/src/dev/components/DeveloperPlayground.vue
allow .md files in developer playground for SuperEditor
=> fix: automatically insert blank docx if SuperEditor file is not docx type

packages/super-editor/src/components/toolbar/defaultItems.js
Strikethrough is not active on the toolbar even if the selected text has it. This happens because the mark is added with the `strike` name, but the toolbar is added as `strikethrough`. So, when the [updateToolbarState](https://github.com/Harbour-Enterprises/SuperDoc/blob/develop/packages/super-editor/src/components/toolbar/super-toolbar.js#L713) function is called, it doesn't set it as active.
=> HAR-10370 - fix: strikethrough not active on toolbar

packages/super-editor/src/extensions/bold/bold.js, packages/super-editor/src/extensions/highlight/highlight.js, packages/super-editor/src/extensions/italic/italic.js, packages/super-editor/src/extensions/link/link.js, packages/super-editor/src/extensions/strike/strike.js, packages/super-editor/src/extensions/text-style/text-style.js, packages/super-editor/src/extensions/underline/underline.js
- Added JSDoc comments for commands in Bold, Highlight, Italic, Strike, Underline, and Link extensions.
- Improved clarity on command usage with examples and parameter descriptions.
- Organized module metadata for better integration with documentation tools.
=> feat: enhance text formatting extensions with detailed command

package.json, packages/super-editor/src/core/helpers/isInTable.js, packages/super-editor/src/extensions/bold/bold.js, packages/super-editor/src/extensions/highlight/highlight.js, packages/super-editor/src/extensions/italic/italic.js, packages/super-editor/src/extensions/link/link.js, packages/super-editor/src/extensions/strike/strike.js, packages/super-editor/src/extensions/structured-content/document-section.js, packages/super-editor/src/extensions/table-cell/helpers/createCellBorders.js, packages/super-editor/src/extensions/table-cell/table-cell.js, packages/super-editor/src/extensions/table-header/table-header.js, packages/super-editor/src/extensions/table-row/table-row.js, packages/super-editor/src/extensions/table/table.js, packages/super-editor/src/extensions/table/tableHelpers/cellAround.js, packages/super-editor/src/extensions/table/tableHelpers/cellWrapping.js, packages/super-editor/src/extensions/table/tableHelpers/createCell.js, packages/super-editor/src/extensions/table/tableHelpers/createColGroup.js, packages/super-editor/src/extensions/table/tableHelpers/createTable.js, packages/super-editor/src/extensions/table/tableHelpers/createTableBorders.js, packages/super-editor/src/extensions/table/tableHelpers/deleteTableWhenSelected.js, packages/super-editor/src/extensions/table/tableHelpers/getColStyleDeclaration.js, packages/super-editor/src/extensions/table/tableHelpers/isCellSelection.js, packages/super-editor/src/extensions/underline/underline.js
- Added keyboard shortcuts for bold (Mod-b, Mod-B), italic (Mod-i, Mod-I), underline (Mod-u, Mod-U), highlight (Mod-Shift-h), and strikethrough (Mod-Shift-s).
- Enhanced table module with detailed configuration options, commands, and helper functions for better usability and documentation clarity.
=> feat: add table module documentation + keyboard shortcuts

packages/super-editor/src/core/DocxZipper.js, packages/super-editor/src/core/DocxZipper.test.js, packages/super-editor/src/core/encoding-helpers.js, packages/super-editor/src/core/encoding-helpers.test.js
- Files encoded with UTF-16 will break DocxZipper. This fixes it.
- OOXML allows UTF-16LE, UTF-16BE so we handle this now
=> fix: imports encoded in utf-16 break DocxZipper

packages/ooxml-inspector/src/children/cli.js, packages/super-editor/src/core/Node.js, packages/super-editor/src/core/OxmlNode.js, packages/super-editor/src/core/Schema.js, packages/super-editor/src/core/index.js, packages/super-editor/src/core/super-converter/SuperConverter.js, packages/super-editor/src/core/super-converter/v2/handlers/index.js, packages/super-editor/src/core/super-converter/v2/handlers/registry/handler-registry.js, packages/super-editor/src/core/super-converter/v2/handlers/registry/handler-registry.test.js, packages/super-editor/src/core/super-converter/v2/handlers/registry/index.js, packages/super-editor/src/core/super-converter/v2/handlers/registry/logger.js, packages/super-editor/src/core/super-converter/v2/handlers/registry/logger.test.js, packages/super-editor/src/core/types/index.js, packages/super-editor/vite.config.js
- Adds new OxmlNode (extends Node) for nodes that we fully migrate to mirror MS Word
- Connects ooxml-inspector (soon to be renamed ooxml-oracle) with super-editor
- Adds set up for handler registry, connect to super converter
- types fixes and improvements
=> Prepare for node translator (import/export upgrades), OxmlNode

packages/super-editor/src/core/super-converter/exporter.js
Hi @harbournick. Not sure if I can add some tests for it because most probably this content was either copied and pasted from somewhere or added via API. It's not possible to have px for line height when importing fro docx
=> fix: add processing for line-height defined in px

packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.js, packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.test.js
- default `w:type="page"` when exporting `hardBreak` nodes lacking `lineBreakType`
- add regression test for `hardBreak` export
=> fix: retain page break when exporting hardBreak

packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/index.js, packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/w-tab-leader.js, packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/w-tab-position.js, packages/super-editor/src/core/super-converter/v3/handlers/w/tab/tab-translator.js, packages/super-editor/src/core/super-converter/v3/handlers/w/tab/tab-translator.test.js, packages/super-editor/src/extensions/tab/tab.js
- handle `w:pos` and `w:leader` on `w:tab` elements
- ensure tab node extension preserves new attributes
- cover new attributes in tab translator tests
- streamline attribute cleanup using shared mapping
=> feat: support additional tab attributes

packages/super-editor/src/extensions/heading/heading.js, packages/super-editor/src/extensions/heading/heading.test.js, packages/super-editor/src/extensions/linked-styles/helpers.js, packages/super-editor/src/extensions/linked-styles/linked-styles.js, packages/super-editor/src/extensions/linked-styles/linked-styles.test.js, packages/super-editor/src/extensions/paragraph/paragraph.js, packages/super-editor/src/extensions/paragraph/paragraph.test.js
- Modifies how headings are parsed so that they are represented as styled paragraphs
- Turns the heading node into an extension
- Adds tests to commands in the linked-styles extension
- Adds tests to commands in the heading extension
=> feat: remove the heading node from superdoc

packages/super-editor/src/components/SuperEditor.vue, packages/super-editor/src/components/toolbar/super-toolbar.js, packages/super-editor/src/core/Editor.js, packages/super-editor/src/core/super-converter/SuperConverter.js, packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js, packages/super-editor/src/extensions/image/imageHelpers/startImageUpload.js, packages/superdoc/src/core/SuperDoc.js
Hi @harbournick! Tested Superdoc's onException hook and it catches unhandled import exceptions. Added another event on document export error. 
We have some try/catch blocks in the import/export process. How do you think should I also emit exception event there if there is a handler for error?
=> fix: emit editor exception on import/export errors

packages/super-editor/src/core/Editor.js, packages/super-editor/src/core/helpers/htmlSanitizer.js, packages/super-editor/src/extensions/paragraph/paragraph.js, packages/superdoc/src/dev/components/SuperdocDev.vue
- Added `exportHTML` method in SuperdocDev.vue to allow users to export editor content as HTML.
- Updated `getHTML` method in Editor.js to include options for unflattening lists.
- Refactored attribute handling in htmlSanitizer.js and paragraph.js to support new `styleid` attribute and improve attribute preservation logic.
=> fix: html import parse styleId attr for round-trip fidelity

packages/super-editor/src/assets/styles/extensions/structured-content.css
Before:
After:
Note:
- This solution is well supported today and makes sense to me. However, this can be solved in another way if support for older browsers is required.
https://caniuse.com/css-has
=> fix: structured content style with image

packages/super-editor/src/core/Editor.js, packages/super-editor/src/core/super-converter/SuperConverter.js, packages/super-editor/src/core/super-converter/SuperConverter.test.js, packages/super-editor/src/core/super-converter/exporter-docx-defs.js, packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js, packages/super-editor/src/tests/import/docxImporter.test.js, shared/common/Telemetry.js
- Renamed `updateDocumentVersion` to `setDocumentVersion` for clarity.
- Introduced methods to get and set SuperDoc ID and version in `SuperConverter`.
- Improved error handling and structure for custom properties in docx.
- Added unit tests for new functionality in `SuperConverter`.
Notes:
- MD5 hash (when GUID present)
- Insert GUID on key stroke
- Do not count on blank document
=> refactor: update document version handling and add SuperDoc ID [SD-428]
