Harbour-Enterprises/SuperDoc

packages/superdoc/src/stores/hrbr-fields-store.js

This reverts commit 0cd9f21929d5502595cddd07860dc978f5f307fc.

Revert "fix pdf preview scale"

---

packages/super-editor/src/core/Editor.js
packages/super-editor/src/extensions/field-annotation/field-annotation.js
packages/super-editor/src/extensions/image/imageHelpers/getImageFileDimensions.js
packages/super-editor/src/extensions/image/imageHelpers/imagePlaceholderPlugin.js
packages/super-editor/src/extensions/image/imageHelpers/startImageUpload.js

- Additional fixes to images (non-field) for pagination

Additional pagination fixes for uploaded images

---

packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/migrations/index.js
packages/super-editor/src/core/migrations/migration_after_0_4_14.js
packages/super-editor/src/core/super-converter/SuperConverter.js
packages/super-editor/src/core/super-converter/exporter-docx-defs.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/vite.config.js

- Adds new collaboration doc migration system
- Adds first migration for post 0.4.14
- Store editor version inside the docx xml

HAR-8956 - Add collaboration migration system, add first migration, store editor version in docx

---

packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/extensions/editorFocus.js
packages/super-editor/src/core/super-converter/SuperConverter.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/listImporter.js
packages/super-editor/src/extensions/list-item/helpers/styledListMarkerPlugin.js
packages/super-editor/src/extensions/text-align/text-align.js
packages/super-editor/src/tests/export/lists/listWithSpacerNodes.test.js
packages/super-editor/src/tests/export/lists/miscOrderedListExport.test.js
packages/super-editor/src/tests/import/listImporter.test.js

Issue: Weird behavior in the toolbar because when I highlight the left justified text, the tool bar updates to the justified icon. But to actually justify it you have to click the icon.

HAR-8934 Text justify toolbar icon issue

---

packages/super-editor/src/assets/styles/elements/prosemirror.css
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/tableImporter.js
packages/super-editor/src/extensions/table-cell/table-cell.js
packages/super-editor/src/extensions/table/table.js

Tables styles fixes and nil borders export fixes

HAR-8846 table import/export fixes

---

package-lock.json
package.json
packages/super-editor/package.json
packages/super-editor/vite.config.js
packages/superdoc/package.json
packages/superdoc/src/SuperDoc.vue
packages/superdoc/src/components/CommentsLayer/CommentDialog.vue
packages/superdoc/src/components/CommentsLayer/CommentGroup.vue
packages/superdoc/src/components/CommentsLayer/CommentsLayer.vue
packages/superdoc/src/components/CommentsLayer/FloatingComments.vue
packages/superdoc/src/components/CommentsLayer/InternalDropdown.vue
packages/superdoc/src/components/CommentsLayer/use-conversation.js
packages/superdoc/src/components/HrbrFieldsLayer/HrbrFieldsLayer.vue
packages/superdoc/src/components/PdfViewer/PdfViewer.vue
packages/superdoc/src/composables/use-document.js
packages/superdoc/src/dev/components/SuperdocDev.vue
packages/superdoc/src/index.js
packages/superdoc/src/stores/comments-store.js
packages/superdoc/src/stores/hrbr-fields-store.js
packages/superdoc/src/stores/superdoc-store.js
packages/superdoc/src/super-editor.js
packages/superdoc/vite.config.js

- Leans on workspace for npm run dev to hot reload if changes are made to super editor
- Fixes issues in build
- Cleans up pass-through super editor exports in superdoc build

HAR-9074 - Refactors the separate packages to lean on the workspace, updates pass-through exports

---

packages/super-editor/src/core/super-converter/exporter.js

Getting a proper signature scale in order to make it more clear in the final doc

HAR-8995 Blurred signature fields(typed signature)

---

package-lock.json
packages/super-editor/package.json
packages/super-editor/src/assets/styles/elements/prosemirror.css
packages/super-editor/src/extensions/gapcursor/gapcursor.js
packages/super-editor/src/extensions/gapcursor/index.js
packages/super-editor/src/extensions/index.js

Fix for the issue.
https://github.com/ProseMirror/prosemirror-tables/issues/5

HAR-8936 - add gapcursor extension

---

packages/super-editor/src/components/toolbar/defaultItems.js
packages/super-editor/src/components/toolbar/toolbarIcons.js
packages/super-editor/src/extensions/table/table.js

HAR-9152 - delete cell and table borders

---

packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/super-converter/SuperConverter.js
packages/super-editor/src/core/super-converter/v2/exporter/commentsExporter.js
packages/superdoc/src/core/SuperDoc.js

- fix comments export for docx files that don't have previous comments infra (ie: comments.xml etc)
- fix pdf export

HAR-9165 Fix comments export for docx files that don't have previous comments infra

---

packages/super-editor/src/components/toolbar/defaultItems.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/superdoc/src/SuperDoc.vue
packages/superdoc/src/components/CommentsLayer/CommentDialog.vue
packages/superdoc/src/components/CommentsLayer/CommentHeader.vue
packages/superdoc/src/components/CommentsLayer/FloatingComments.vue
packages/superdoc/src/components/CommentsLayer/use-comment.js
packages/superdoc/src/stores/comments-store.js

- Adds creating SuperDoc comments from tracked changes (suggestions)
- Updates comment positions based on doc changes
- Removes comments on resolve or reject
- Removes previous toolbar buttons (temporary) for resolve and reject

HAR-8708 - Tracked change comments

---

packages/super-editor/src/components/toolbar/ButtonGroup.vue
packages/super-editor/src/components/toolbar/Toolbar.vue
packages/super-editor/src/components/toolbar/ToolbarButton.vue
packages/super-editor/src/components/toolbar/defaultItems.js
packages/super-editor/src/components/toolbar/super-toolbar.js

Fixed toolbar reactivity and responsiveness following the current approach.
Note:
I think the approach should be reconsidered and changed later.

HAR-9170 - fix toolbar reactivity and responsiveness

---

packages/super-editor/src/extensions/pagination/pagination.js

- Fixes issue with hidden editor (for pagination) not getting the right styles, causing various calculations to be off
- Fixes header height calculation

Fix header height min calculation, fix hidden editor styles missing

---

packages/super-editor/src/components/SuperInput.vue
packages/super-editor/src/components/popovers/Mentions.vue
packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/super-converter/SuperConverter.js
packages/super-editor/src/core/super-converter/exporter-docx-defs.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/exporter/commentsExporter.js
packages/super-editor/src/extensions/comment/comments-helpers.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/super-editor/src/tests/export/lists/commentExport.test.js
packages/superdoc/src/SuperDoc.vue
packages/superdoc/src/components/CommentsLayer/CommentDialog.vue
packages/superdoc/src/components/CommentsLayer/CommentHeader.vue
packages/superdoc/src/components/CommentsLayer/FloatingComments.vue
packages/superdoc/src/stores/comments-store.js

- Adds export for threaded comments
- Adds additional logic needed at export for file generation
- Adds schema for commentsExtended.xml, commentsExtensible.xml, commentsIds.xml, comments.xml, document.xml.rels
- Adds scroll-to-comment by url param (for direct-to-comment links)
- Fixes collaboration sync for accept/reject suggestion
- Fixes various floating comments issues
- Other minor tweaks

HAR-9198 - Comments

---

packages/super-editor/src/extensions/track-changes/track-changes.js

- When tracked change has both add/delete, we need to resolve or reject both at the same time.

HAR-9198 - Fix resolving dual add/delete tracked change

---

packages/super-editor/src/extensions/comment/comments-plugin.js
packages/superdoc/src/SuperDoc.vue
packages/superdoc/src/core/collaboration/helpers.js
packages/superdoc/src/stores/comments-store.js

- Fixes floating comments init
- Fixes race case between comments collaboration sync and editor locations emit
- Fixes issue with floating comments having no selectionBounds on init

HAR-9157 - Trigger floating comment init on sync or locations emit 

---

packages/super-editor/src/assets/styles/elements/prosemirror.css
packages/super-editor/src/core/super-converter/exporter.js

Fixed images and field annotations (images/signatures) in import/export.
Note:
- This does not fix the image export issue that was introduced with one of the previous PRs.

HAR-9224 - fix export images inside table

---

packages/super-editor/src/extensions/comment/comments-plugin.js
packages/super-editor/src/extensions/track-changes/trackChangesHelpers/trackedTransaction.js
packages/superdoc/src/SuperDoc.vue
packages/superdoc/src/dev/components/SuperdocDev.vue

- Fix pending comment being overriden by setActiveComment when change and comment overlap
- Allow setting user role, email from url params in SuperDoc dev

HAR-9280 - Fix pending comment being overriden by setActiveComment when change and comment overlap

---

packages/super-editor/src/extensions/comment/comments-helpers.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/super-editor/src/extensions/track-changes/trackChangesHelpers/addMarkStep.js
packages/super-editor/src/extensions/track-changes/trackChangesHelpers/trackedTransaction.js
packages/superdoc/src/SuperDoc.vue

- Fix ID for tracked format change
- Fix detection of tracked format change for comments
- Add human-readbale summary of tracked format changes

HAR-9274 - Tracked formatting changes

---

packages/super-editor/src/extensions/pagination/pagination.js

Added changes that break tables more accurately (for pagination). If a node exceeds the page size and it is located in a table cell, then other cells are not taken into account. I think in this case we should break the tableRow instead.
Before.
After.

HAR-9297 - pagination: break table row instead of cell if found

---

packages/superdoc/src/components/CommentsLayer/CommentDialog.vue
packages/superdoc/src/components/CommentsLayer/CommentHeader.vue
packages/superdoc/src/core/collaboration/helpers.js
packages/superdoc/src/core/collaboration/permissions.js
packages/superdoc/src/stores/comments-store.js

- Fix missing comment header in external comments 
- Allow overflow in child comments
- Fix permissions for edit/delete comment with internal/external
- Fixes comment deletion

HAR-9261 - Comment permissions fixes, dialog fixes

---

packages/super-editor/src/components/toolbar/super-toolbar.js
packages/superdoc/src/SuperDoc.vue
packages/superdoc/src/core/SuperDoc.js

Fixed updating the toolbar state when initialized and when updating the document mode.
@harbournick Please double check before merging as I'm not aware of the details of  `SuperToolbar` and `SuperDoc` classes.

HAR-9336 - fix toolbar state updates

---

packages/super-editor/src/core/super-converter/v2/exporter/commentsExporter.js
packages/super-editor/src/core/super-converter/v2/importer/documentCommentsImporter.js
packages/super-editor/src/extensions/comment/comments-helpers.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/superdoc/src/stores/comments-store.js

- fix comment import
- removes importedId at import, assigns commentId from import
- fix comment export for importedAuthor
- fix setting active comment ID in comments plugin

Comments plugin fixes

---

packages/super-editor/src/core/helpers/getActiveFormatting.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/superdoc/src/components/CommentsLayer/FloatingComments.vue
packages/superdoc/src/stores/comments-store.js

- Fixes issue with floating comments sidebar flickering when there are no comments (only tracked change comments)
- Fixes transaction dispatch on selection change in comments plugin

HAR-9366 - Fix issue with floating comments ignoring tracked changes when no comments

---

packages/super-editor/src/core/helpers/createDocument.js
packages/super-editor/src/core/super-converter/SuperConverter.js
packages/super-editor/src/core/super-converter/v2/importer/annotationImporter.js
packages/super-editor/src/core/super-converter/v2/importer/listImporter.js
packages/super-editor/src/core/super-converter/v2/importer/standardNodeImporter.js

Fixed import issues that prevented import of a specific document.

HAR-9246 - handle import issues

---

packages/super-editor/src/core/super-converter/v2/exporter/commentsExporter.js
packages/super-editor/src/core/super-converter/v2/importer/documentCommentsImporter.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/super-editor/src/extensions/track-changes/trackChangesHelpers/addMarkStep.js
packages/super-editor/src/extensions/track-changes/trackChangesHelpers/removeMarkStep.js
packages/super-editor/src/extensions/track-changes/trackChangesHelpers/replaceStep.js
packages/superdoc/src/stores/comments-store.js

HAR-9380, HAR-9382 and HAR-9383

HAR-9380 - track changes and comments fixes

---

packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/ExtensionService.js
packages/super-editor/src/core/InputRule.js
packages/super-editor/src/core/commands/index.js
packages/super-editor/src/core/commands/undoInputRule.js
packages/super-editor/src/core/extensions/keymap.js
packages/super-editor/src/core/helpers/getHTMLFromFragment.js
packages/super-editor/src/core/helpers/getTextContentFromNodes.js
packages/super-editor/src/core/helpers/isExtentionRulesEnabled.js
packages/super-editor/src/core/inputRules/wrappingInputRule.js
packages/super-editor/src/core/utilities/isRegExp.js
packages/super-editor/src/core/utilities/objectIncludes.js
packages/super-editor/src/extensions/bullet-list/bullet-list.js
packages/super-editor/src/extensions/ordered-list/ordered-list.js

1. Creates bullet list by typing '- '
2. Creates ordered list by typing '1. + Enter'

Lists input rules

---

packages/superdoc/src/components/PdfViewer/PdfViewer.vue

This causes issues with document resizing and fields positions in mobile. Before resizing the document for mobile width, we need to show the pages at their original size so that the fields have the correct positions. 
We will show the loader first until all pages are rendered and only then append.

HAR-9472 - show pages when pdf document is rendered

---

packages/super-editor/src/core/super-converter/v2/importer/listImporter.js
packages/super-editor/src/core/super-converter/v2/importer/paragraphNodeImporter.js
packages/super-editor/src/tests/export/lists/testComplexListIssues.test.js

- Fixes various issues around recursive list definitions
- adds support for outlineLvl instead of ilvl tags

Fixes various recursive list definitions, outline numbering

---

packages/super-editor/src/core/Editor.js
packages/superdoc/src/SuperDoc.vue
packages/superdoc/src/composables/use-document.js
packages/superdoc/src/core/SuperDoc.js
packages/superdoc/src/dev/components/SuperdocDev.vue
packages/superdoc/src/stores/superdoc-store.js

- Adds 'document' key to pass in single file to superdoc (does not remove documents key)
- Adds even simpler default blank docx init
- Adds HTML-to-docx init in SuperDoc

HAR-9556 - Updates to SuperDoc AP

---

examples/vue-custom-mark/src/App.vue
packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/ExtensionService.js
packages/super-editor/src/core/Mark.js
packages/super-editor/src/core/super-converter/SuperConverter.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/bookmarkNodeImporter.js
packages/super-editor/src/core/super-converter/v2/importer/runNodeImporter.js

- Add a mechanism to serialize/deserialize custom external marks

HAR-9577 - Serialize/deserialize external/custom marks

---

packages/super-editor/src/assets/styles/elements/prosemirror.css
packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/alternateChoiceImporter.js
packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js
packages/super-editor/src/core/super-converter/v2/importer/imageImporter.js
packages/super-editor/src/extensions/content-block/content-block.js
packages/super-editor/src/extensions/content-block/index.js
packages/super-editor/src/extensions/index.js

Changes from this PR are used here as a basis.
https://github.com/Harbour-Enterprises/SuperDoc/pull/478

HAR-9460 - handle alternate content node

---

packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js
packages/super-editor/src/core/super-converter/v2/importer/paragraphNodeImporter.js
packages/super-editor/src/core/super-converter/v2/importer/tabImporter.js
packages/super-editor/src/extensions/line-break/line-break.js
packages/super-editor/src/extensions/pagination/pagination-helpers.js
packages/super-editor/src/extensions/pagination/pagination.js
packages/super-editor/src/extensions/paragraph/paragraph.js
packages/super-editor/src/extensions/tab/tab.js

- Fixes around haders/footers when there's a sectPr page break
- Fixes to first page header/footer id
- Adds page breaks on sectPr

HAR-9637 - SD header/footer fixes

---

packages/super-editor/src/components/toolbar/defaultItems.js
packages/super-editor/src/core/Editor.js
packages/super-editor/src/extensions/index.js
packages/super-editor/src/extensions/search/index.js
packages/super-editor/src/extensions/search/search.js
packages/superdoc/src/core/SuperDoc.js

- Move search code to use extension
- Use editor.commands for search
- Add search to SuperDoc.js
- Return matches from command

Search tweaks

---

packages/super-editor/src/assets/styles/elements/prosemirror.css
packages/super-editor/src/assets/styles/elements/toolbar-custom.css
packages/super-editor/src/assets/styles/elements/toolbar.css
packages/super-editor/src/assets/styles/extensions/comments.css
packages/super-editor/src/assets/styles/extensions/mention.css
packages/super-editor/src/assets/styles/extensions/pagination.css
packages/super-editor/src/assets/styles/extensions/placeholder.css
packages/super-editor/src/assets/styles/extensions/popover.css
packages/super-editor/src/assets/styles/layout/global.css
packages/super-editor/src/components/toolbar/ButtonGroup.vue
packages/super-editor/src/extensions/ai/ai-marks.js
packages/super-editor/src/extensions/comment/comments-marks.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/super-editor/src/extensions/mention/mention.js
packages/super-editor/src/extensions/paragraph/paragraph.js
packages/super-editor/src/extensions/placeholder/placeholder.js
packages/super-editor/src/extensions/popover-plugin/popover-plugin.js
packages/super-editor/src/extensions/shape-container/shape-container.js
packages/super-editor/src/extensions/shape-textbox/shape-textbox.js
packages/super-editor/src/extensions/tab/tab.js
packages/superdoc/src/assets/styles/layout/global.css
packages/superdoc/src/components/CommentsLayer/CommentDialog.vue
packages/superdoc/src/components/CommentsLayer/CommentGroup.vue
packages/superdoc/src/components/CommentsLayer/CommentInput.vue
packages/superdoc/src/components/CommentsLayer/CommentsLayer.vue
packages/superdoc/src/components/PdfViewer/PdfViewer.vue
packages/superdoc/src/stores/comments-store.js
shared/common/styles/common-styles.css

Note: see comment in linear ticket.

HAR-9647 - improve styles encapsulation

---

packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/annotationImporter.js
packages/super-editor/src/dev/components/DeveloperPlayground.vue

Added comments in the code explaining the changes.

HAR-9653 - improve import and export of html annotation

---

packages/super-editor/src/core/extensions/keymap.js

Commands (in this case handlers) must return the result.

HAR-9578 - return result from keymap handlers

---

packages/super-editor/src/components/toolbar/super-toolbar.js
packages/super-editor/src/core/helpers/getActiveFormatting.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/annotationImporter.js
packages/super-editor/src/dev/components/DeveloperPlayground.vue
packages/super-editor/src/extensions/field-annotation/field-annotation.js
packages/super-editor/src/extensions/table/table.js

- Text highlight and color for field annotations (including html/paragraph fields).
- Background for table cells.

HAR-9709, HAR-9712 - highlight for field annotation and table cell

---

packages/super-editor/src/core/super-converter/SuperConverter.js
packages/super-editor/src/core/super-converter/constants.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/tests/export/annotations/fieldAnnotationExporter.test.js
packages/super-editor/src/tests/export/annotations/fieldAnnotationFinalDoc.test.js

Added comments in the code (more details in the ticket).

HAR-9736 - fix link export (and url field)

---

packages/super-editor/src/assets/styles/elements/prosemirror.css
packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/InputRule.js
packages/super-editor/src/core/commands/insertTabNode.js
packages/super-editor/src/core/inputRules/docx-paste/docx-paste.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/extensions/index.js
packages/super-editor/src/extensions/list-item/list-item.js
packages/super-editor/src/extensions/ordered-list/ordered-list.js
packages/super-editor/src/tests/export/export-helpers/export-helpers.js

- Adds special handling to lists when copy/paste from MS word into docx editor
- Fixes a bug with 'tab' key in html editor
- Adds various attributes to convert to/from html and docx in lists

HAR-9765 - Add special handler for lists when copy-paste from MS Word

---

packages/super-editor/src/components/toolbar/ButtonGroup.vue
packages/super-editor/src/components/toolbar/LinkedStyle.vue
packages/super-editor/src/components/toolbar/defaultItems.js

Added for:
- zoom.
- font-family.
- font-size.
- line-height.
- linked styles.

HAR-9741 - add select class to dropdowns

---

packages/super-editor/src/core/EventEmitter.js

- Adds handler for '.once' in custom event emitter class

HAR-9817 - Add .once to custom event emitter in editor.js

---

packages/superdoc/src/core/SuperDoc.js
packages/superdoc/src/core/collaboration/helpers.js
packages/superdoc/src/dev/components/SuperdocDev.vue
packages/superdoc/src/stores/comments-store.js

- Use primary ydoc for all comments if not using internal/external comments

HAR-9770 - Use main document ydoc for all comments if not using internal/external comments

---

packages/super-editor/src/components/SuperEditor.vue
packages/super-editor/src/components/toolbar/ButtonGroup.vue
packages/super-editor/src/components/toolbar/Toolbar.vue
packages/super-editor/src/components/toolbar/ToolbarButton.vue
packages/super-editor/src/components/toolbar/super-toolbar.js

- Added basic keyboard navigation support on the toolbar and its items
- Add shortcut to go back to toolbar when you're focused on the editor
https://github.com/user-attachments/assets/e4784d31-ead5-435e-9c48-aeccea491776

HAR-9796 -  Accessibility keyboard navigation and focus management

---

packages/super-editor/src/assets/styles/elements/_all.css
packages/super-editor/src/assets/styles/elements/page-number.css
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/autoPageNumberImporter.js
packages/super-editor/src/core/super-converter/v2/importer/paragraphNodeImporter.js
packages/super-editor/src/extensions/page-number/page-number.js
packages/super-editor/src/extensions/pagination/pagination-helpers.js
packages/super-editor/src/extensions/pagination/pagination.js

- Fixes auto page number nodes after editable headers/footers changes
- Adds new node view to page-number and total-page-numer
- imports styles and checks styles of neighboring nodes to fix various style issues
- adds export to both numbering nodes
- adds keyboard shortcuts for both numbering nodes

HAR-9859 - Add new handling for page numbers and total page count after editable headers/footers

---

packages/superdoc/package.json
packages/superdoc/src/core/SuperDoc.js
packages/superdoc/src/core/collaboration/collaboration.js
packages/superdoc/src/core/collaboration/helpers.js

- Adds y-websocket (Yjs default) provider as the default collaboration provider
- Requires new providerType flag in collaboration config to use any other provider
- Minor change to awareness

Feature: Add y-websocket provider as default provider

---

packages/super-editor/src/extensions/table/table.js
packages/super-editor/src/extensions/table/tableHelpers/cellAround.js
packages/super-editor/src/extensions/table/tableHelpers/cellWrapping.js

Split table cell into smaller ones if colspan equal to one.

HAR-9896 - split single table cell command

---

packages/super-editor/src/assets/styles/elements/prosemirror.css
packages/super-editor/src/assets/styles/extensions/pagination.css

Disabling editor/header/footer fading feature for now due to race conditions that were found. Will be fixed soon.

chore: disabled fading

---

packages/super-editor/src/extensions/table/table.js

Updated commands:
- `addColumnBefore`
- `addColumnAfter`
- `addRowBefore`
- `addRowAfter`

HAR-9745 - updated table commands

---

packages/super-editor/src/components/toolbar/ButtonGroup.vue
packages/super-editor/src/components/toolbar/ToolbarButton.vue
packages/super-editor/src/components/toolbar/defaultItems.js

- update the control of the font size input
- allow typing in the toolbar
- focuses the input on click

fix: allow toolbar when typing font size

---

packages/super-editor/src/core/Editor.js
packages/super-editor/src/core/commands/deleteListItem.js
packages/super-editor/src/core/commands/deleteSelection.js
packages/super-editor/src/core/commands/splitListItem.js
packages/super-editor/src/core/extensions/keymap.js
packages/super-editor/src/core/helpers/list-numbering-helpers.js
packages/super-editor/src/core/migrations/0.14-listsv2/listsv2migration.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/extensions/bullet-list/bullet-list.js
packages/super-editor/src/extensions/list-item/ListItemNodeView.js
packages/super-editor/src/extensions/list-item/list-item.js
packages/super-editor/src/extensions/ordered-list/helpers/orderedListSyncPlugin.js
packages/super-editor/src/extensions/ordered-list/ordered-list.js
packages/superdoc/src/dev/components/SuperdocDev.vue

- Fixes around various commands
- Collaborative file migration fixes

Feature: Lists v2 - Part 3

---

packages/super-editor/src/assets/styles/extensions/list-items.css
packages/super-editor/src/extensions/list-item/ListItemNodeView.js
packages/super-editor/src/extensions/pagination/pagination.js

- style tweaks to lists numbering
- remove paginate by row

Feature: Lists v2

---

packages/super-editor/src/extensions/pagination/pagination.js

Reverts Harbour-Enterprises/SuperDoc#637

Revert "HAR-9988 Fix page break consider safe position to break"

---

packages/super-editor/src/core/super-converter/exporter.js

Related PR:
https://github.com/Harbour-Enterprises/SuperDoc/pull/665

HAR-10021 - update table cellMinWidth

---

packages/super-editor/src/core/super-converter/v2/importer/tableImporter.js
packages/super-editor/src/tests/import/tableImporter.test.js

Fixed incorrect handling of cell width if inline width is missing and other issues.
See comments in the code.

HAR-10241 - fix table import

---

packages/super-editor/src/core/InputRule.js
packages/super-editor/src/extensions/structured-content/document-section.js
packages/super-editor/tsconfig.json

- Fixes issues in document-sections preventing build if ts-ignore is removed
- Adds vite aliases to tsconfig

Doc gen: Add aliases to tsconfig, remove ts-ignore in document sections 

---

package.json
packages/super-editor/src/core/super-converter/v2/importer/trackChangesImporter.js
packages/super-editor/src/extensions/comment/comments-plugin.js
packages/super-editor/src/extensions/track-changes/track-delete.js
packages/super-editor/src/extensions/track-changes/track-format.js
packages/super-editor/src/extensions/track-changes/track-insert.js
packages/super-editor/src/tests/import/trackChangesImporter.test.js
packages/superdoc/package.json
packages/superdoc/src/components/CommentsLayer/CommentHeader.vue
packages/superdoc/src/helpers/group-changes.js
packages/superdoc/src/stores/comments-store.js
packages/superdoc/src/tests/helpers/group-changes.test.js
packages/superdoc/tsconfig.json
packages/superdoc/vite.config.js

1. Show correct comment dialog for track changes
2. Group replace changes into one comment

fix(track changes): fix permissions issue and group replace changes

---

packages/ooxml-inspector/src/children/cli.js
packages/super-editor/src/core/commands/backspaceNextToList.js
packages/super-editor/src/core/commands/decreaseListIndent.js
packages/super-editor/src/core/commands/decreaseListIndent.test.js
packages/super-editor/src/core/commands/toggleList.js

- Fixes issue with list outdent converting from bullet to numbered
- lint fixes

Fix: list outdent and lint

---

packages/super-editor/src/components/toolbar/ButtonGroup.vue
packages/super-editor/src/components/toolbar/constants.js
packages/super-editor/src/components/toolbar/defaultItems.js

fix: highlight selected value in font dropdowns

---

packages/super-editor/src/core/helpers/orderedListUtils.js
packages/super-editor/src/core/helpers/orderedListUtils.test.js
packages/super-editor/src/core/super-converter/v2/importer/listImporter.js

Linear ticket - HAR-10428.
Issue - https://github.com/Harbour-Enterprises/SuperDoc/issues/813

fix: list numbering

---

packages/super-editor/src/core/Attribute.js
packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/docxImporter.js
packages/super-editor/src/core/super-converter/v2/importer/paragraphNodeImporter.js
packages/super-editor/src/core/super-converter/v2/importer/tabImporter.js
packages/super-editor/src/core/super-converter/v3/handlers/index.js
packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.js
packages/super-editor/src/core/super-converter/v3/handlers/w/br/br-translator.test.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/index.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/w-tab-leader.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/w-tab-pos.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tab/attributes/w-tab-size.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tab/index.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tab/tab-translator.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tab/tab-translator.test.js
packages/super-editor/src/core/super-converter/v3/node-translator/node-translator.js
packages/super-editor/src/core/super-converter/v3/node-translator/node-translator.test.js
packages/super-editor/src/extensions/block-node/block-node.js
packages/super-editor/src/index.js
packages/super-editor/src/tests/import-export/tabStopsRoundTrip.test.js
packages/super-editor/tsconfig.json
packages/super-editor/vite.config.js
packages/superdoc/src/core/SuperDoc.js

Adds v3 import/export translator for the tab node, and handles all OOXML attributes.
Adds tsconfig alias for "@translator" for better imports

Add translator v3 for w:tab node

---

packages/super-editor/src/core/super-converter/v2/importer/listImporter.test.js

add tests for https://github.com/Harbour-Enterprises/SuperDoc/commit/a5b43d036133217d6f15661f3b1666d621fee049

chore: add tests for list import fix

---

packages/super-editor/src/core/super-converter/exporter.js
packages/super-editor/src/core/super-converter/v2/importer/tableImporter.js
packages/super-editor/src/core/super-converter/v2/importer/types/index.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/legacy-handle-table-cell-node.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/legacy-handle-table-cell-node.test.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/translate-table-cell.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tc/helpers/translate-table-cell.test.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tc/index.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tc/tc-translator.js
packages/super-editor/src/core/super-converter/v3/handlers/w/tc/tc-translator.test.js

Update table cell import/export to V3.

refactor: update table cell import/export
